# CircleCI config file
version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8
  codecov: codecov/codecov@3.2.5
  node: circleci/node@5.1.0

# Define the jobs we want to run for this project
jobs:
  lint-code:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is the lint-code job"
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
  test:
    executor: node/default
    steps:
      - run: npm test
  deploy-netlify:
    executor: node/default
    steps:
      - run: npm run deploy:netlify
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.foo.software,https://www.foo.software/contact
  codecov:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run test:coverage
      - codecov/upload:
          file: "./coverage/clover.xml"

# Orchestrate our job run sequence
workflows:
  lint_build_test_deploy:
    jobs:
      - lint-code
      - build:
          requires:
            - lint-code
      - test:
          requires:
            - build
      - deploy-netlify:
          requires:
            - test
  analyze:
    jobs:
      - lighthouse
      - codecov
