# CircleCI config file
version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8
  codecov: codecov/codecov@3.2.5
  node: circleci/node@5.1.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is the test job"
  deploy-netlify:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
      - run: npm run netlify:deploy
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.foo.software,https://www.foo.software/contact
  lighthouse-badges:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run lighthouse-badges
      - run: npm run lighthouse-badges-single
  codecov:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run test:coverage
      - codecov/upload:
          file: "./coverage/clover.xml"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
  deploy:
    jobs:
      - deploy-netlify
  analyze:
    jobs:
      - lighthouse
      - codecov
